---
version: "3"
services:
  oauth-server:
    image: 192.168.8.197:5000/bmsoft/bmsoft-oauth-server:c.2.3-SNAPSHOT
    ports:
      - 8773:8773
    volumes:
      - /data/:/data
    environment: 
      - NACOS_IP=192.168.1.34
      - NACOS_PORT=8848
      - NACOS_ID=bmsoft-cloud
    deploy:
      mode: replicated
      replicas: 1
      
  authority-server:
    image: 192.168.8.197:5000/bmsoft/bmsoft-authority-server:c.2.3-SNAPSHOT
    ports:
      - 8764:8764
    volumes:
      - /data/:/data
    environment: 
      - NACOS_IP=192.168.1.34
      - NACOS_PORT=8848
      - NACOS_ID=bmsoft-cloud
    deploy:
      mode: replicated
      replicas: 1

  msgs-server:
    image: 192.168.8.197:5000/bmsoft/bmsoft-msgs-server:c.2.3-SNAPSHOT
    ports:
      - 8768:8768
    volumes:
      - /data/:/data
    environment: 
      - NACOS_IP=192.168.1.34
      - NACOS_PORT=8848
      - NACOS_ID=bmsoft-cloud
    deploy:
      mode: replicated
      replicas: 1
      
  files-server:
    image: 192.168.8.197:5000/bmsoft/bmsoft-file-server:c.2.3-SNAPSHOT
    ports:
      - 8765:8765
    volumes:
      - /data/:/data
    environment: 
      - NACOS_IP=192.168.1.34
      - NACOS_PORT=8848
      - NACOS_ID=bmsoft-cloud
    deploy:
      mode: replicated
      replicas: 1
 
  gateway-server:
    image: 192.168.8.197:5000/bmsoft/bmsoft-gateway-server:c.2.3-SNAPSHOT
    ports:
      - 8760:8760
    volumes:
      - /data/:/data
    environment: 
      - NACOS_IP=192.168.1.34
      - NACOS_PORT=8848
      - NACOS_ID=bmsoft-cloud
    deploy:
      mode: replicated
      replicas: 1
 
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]